<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PendaftarSeeder extends Seeder
{
    public function run(): void
    {
        $pendaftars = [
            // --- Peserta 1: Andi (diterima, lunas, di angkatan On_Going TB) ---
            [
                'id'                      => 'PD-000000-0000-0000-000000000001',
                'no_pendaftaran'          => 'LPK-2026-00001',
                'tanggal_daftar'          => '2026-03-10 09:00:00',
                'status'                  => 'diterima',
                'nama_lengkap'            => 'Andi Pratama',
                'nik'                     => '3201011504970001',
                'tempat_lahir'            => 'Bandung',
                'tanggal_lahir'           => '1997-04-15',
                'jenis_kelamin'           => 'Laki-laki',
                'alamat'                  => 'Jl. Sudirman No. 12, Bandung, Jawa Barat',
                'tinggi_badan'            => '172',
                'berat_badan'             => '68',
                'lingkar_pinggang'        => '80',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567801',
                'email'                   => 'andi.pratama@gmail.com',
                'nama_kontak_darurat'     => 'Slamet Pratama',
                'no_hp_kontak_darurat'    => '081234567900',
                'hubungan_kontak_darurat' => 'Ayah',
                'jenis_pelatihan'         => 'Tata Boga & Pastry',
                'program_id'              => 'PROG-TATA-BOGA',
                'motivasi'                => 'Saya ingin mengembangkan skill memasak dan membuka usaha catering sendiri setelah lulus.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000002',
                'user_id'                 => '22222222-0000-0000-0000-000000000001',
                'biaya_pelatihan'         => 4500000,
                'status_pembayaran'       => 'lunas',
                'jenis_pembayaran'        => 'lunas',
                'metode_pembayaran'       => 'Transfer Bank',
                'bukti_pembayaran'        => 'bukti/pembayaran/andi-pratama-lunas.jpg',
                'tanggal_bayar'           => '2026-04-01 10:30:00',
            ],
            // --- Peserta 2: Siti (diterima, cicilan, di angkatan On_Going TB) ---
            [
                'id'                      => 'PD-000000-0000-0000-000000000002',
                'no_pendaftaran'          => 'LPK-2026-00002',
                'tanggal_daftar'          => '2026-03-12 10:00:00',
                'status'                  => 'diterima',
                'nama_lengkap'            => 'Siti Rahayu',
                'nik'                     => '3275014506990002',
                'tempat_lahir'            => 'Jakarta',
                'tanggal_lahir'           => '1999-06-05',
                'jenis_kelamin'           => 'Perempuan',
                'alamat'                  => 'Jl. Kebon Jeruk No. 45, Jakarta Barat',
                'tinggi_badan'            => '158',
                'berat_badan'             => '52',
                'lingkar_pinggang'        => '68',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567802',
                'email'                   => 'siti.rahayu@gmail.com',
                'nama_kontak_darurat'     => 'Aminah',
                'no_hp_kontak_darurat'    => '081234567901',
                'hubungan_kontak_darurat' => 'Ibu',
                'jenis_pelatihan'         => 'Tata Boga & Pastry',
                'program_id'              => 'PROG-TATA-BOGA',
                'motivasi'                => 'Ingin menjadi pastry chef profesional dan bekerja di hotel bintang lima.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000002',
                'user_id'                 => '22222222-0000-0000-0000-000000000002',
                'biaya_pelatihan'         => 4500000,
                'status_pembayaran'       => 'cicilan_sebagian',
                'jenis_pembayaran'        => 'cicilan',
                'metode_pembayaran'       => 'Transfer Bank',
                'bukti_pembayaran'        => 'bukti/pembayaran/siti-rahayu-dp.jpg',
                'tanggal_bayar'           => '2026-04-02 11:00:00',
            ],
            // --- Peserta 3: Rizky (diterima, lunas, di angkatan On_Going TB) ---
            [
                'id'                      => 'PD-000000-0000-0000-000000000003',
                'no_pendaftaran'          => 'LPK-2026-00003',
                'tanggal_daftar'          => '2026-03-15 13:00:00',
                'status'                  => 'diterima',
                'nama_lengkap'            => 'Rizky Maulana',
                'nik'                     => '3578010310010003',
                'tempat_lahir'            => 'Surabaya',
                'tanggal_lahir'           => '2001-03-03',
                'jenis_kelamin'           => 'Laki-laki',
                'alamat'                  => 'Jl. Raya Darmo No. 88, Surabaya, Jawa Timur',
                'tinggi_badan'            => '175',
                'berat_badan'             => '72',
                'lingkar_pinggang'        => '82',
                'riwayat_penyakit'        => 'Alergi seafood',
                'no_hp'                   => '081234567803',
                'email'                   => 'rizky.maulana@gmail.com',
                'nama_kontak_darurat'     => 'Hendra Maulana',
                'no_hp_kontak_darurat'    => '081234567902',
                'hubungan_kontak_darurat' => 'Kakak',
                'jenis_pelatihan'         => 'Tata Boga & Pastry',
                'program_id'              => 'PROG-TATA-BOGA',
                'motivasi'                => 'Bermimpi membuka restoran keluarga yang berkualitas tinggi.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000002',
                'user_id'                 => '22222222-0000-0000-0000-000000000003',
                'biaya_pelatihan'         => 4500000,
                'status_pembayaran'       => 'lunas',
                'jenis_pembayaran'        => 'lunas',
                'metode_pembayaran'       => 'QRIS',
                'bukti_pembayaran'        => 'bukti/pembayaran/rizky-maulana-lunas.jpg',
                'tanggal_bayar'           => '2026-04-03 09:00:00',
            ],
            // --- Peserta 4: Fitri (menunggu, belum bayar, di angkatan Pendaftaran HK) ---
            [
                'id'                      => 'PD-000000-0000-0000-000000000004',
                'no_pendaftaran'          => 'LPK-2026-00004',
                'tanggal_daftar'          => '2026-08-20 14:30:00',
                'status'                  => 'menunggu',
                'nama_lengkap'            => 'Fitri Handayani',
                'nik'                     => '3471024508020004',
                'tempat_lahir'            => 'Yogyakarta',
                'tanggal_lahir'           => '2002-08-05',
                'jenis_kelamin'           => 'Perempuan',
                'alamat'                  => 'Jl. Malioboro No. 22, Yogyakarta',
                'tinggi_badan'            => '160',
                'berat_badan'             => '55',
                'lingkar_pinggang'        => '70',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567804',
                'email'                   => 'fitri.handayani@gmail.com',
                'nama_kontak_darurat'     => 'Sumarni',
                'no_hp_kontak_darurat'    => '081234567903',
                'hubungan_kontak_darurat' => 'Ibu',
                'jenis_pelatihan'         => 'Housekeeping Hotel',
                'program_id'              => 'PROG-HOUSEKEEPING',
                'motivasi'                => 'Ingin bekerja di hotel bintang di Bali dan meningkatkan taraf hidup keluarga.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000003',
                'user_id'                 => '22222222-0000-0000-0000-000000000004',
                'biaya_pelatihan'         => 2500000,
                'status_pembayaran'       => 'belum_bayar',
                'jenis_pembayaran'        => null,
                'metode_pembayaran'       => null,
                'bukti_pembayaran'        => null,
                'tanggal_bayar'           => null,
            ],
            // --- Peserta 5: Dian (ditolak) ---
            [
                'id'                      => 'PD-000000-0000-0000-000000000005',
                'no_pendaftaran'          => 'LPK-2026-00005',
                'tanggal_daftar'          => '2026-08-21 10:00:00',
                'status'                  => 'ditolak',
                'nama_lengkap'            => 'Dian Permata',
                'nik'                     => '3275091209030005',
                'tempat_lahir'            => 'Depok',
                'tanggal_lahir'           => '2003-09-12',
                'jenis_kelamin'           => 'Perempuan',
                'alamat'                  => 'Jl. Margonda Raya No. 100, Depok, Jawa Barat',
                'tinggi_badan'            => '155',
                'berat_badan'             => '48',
                'lingkar_pinggang'        => '65',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567805',
                'email'                   => 'dian.permata@gmail.com',
                'nama_kontak_darurat'     => 'Heri Permata',
                'no_hp_kontak_darurat'    => '081234567904',
                'hubungan_kontak_darurat' => 'Ayah',
                'jenis_pelatihan'         => 'Housekeeping Hotel',
                'program_id'              => 'PROG-HOUSEKEEPING',
                'motivasi'                => 'Ingin mendapatkan sertifikasi internasional di bidang hospitality.',
                'angkatan_id'             => null,
                'user_id'                 => '22222222-0000-0000-0000-000000000005',
                'biaya_pelatihan'         => 2500000,
                'status_pembayaran'       => 'belum_bayar',
                'jenis_pembayaran'        => null,
                'metode_pembayaran'       => null,
                'bukti_pembayaran'        => null,
                'tanggal_bayar'           => null,
            ],
        ];

        DB::table('pendaftars')->insert($pendaftars);
    }
}
