<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PendaftarSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('pendaftars')->delete();

        $pendaftars = [
            // 1. Andi (diterima, lunas, Angkatan 50)
            [
                'id'                      => 'PD-000000-0000-0000-000000000001',
                'no_pendaftaran'          => 'LPK-2026-00001',
                'tanggal_daftar'          => '2026-03-10 09:00:00',
                'status'                  => 'diterima',
                'nama_lengkap'            => 'Andi Pratama',
                'nik'                     => '3201011504970001',
                'tempat_lahir'            => 'Bandung',
                'tanggal_lahir'           => '1997-04-15',
                'jenis_kelamin'           => 'Laki-laki',
                'alamat'                  => 'Jl. Sudirman No. 12, Leles, Garut, Jawa Barat',
                'tinggi_badan'            => '172',
                'berat_badan'             => '68',
                'lingkar_pinggang'        => '80',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567801',
                'email'                   => 'andi.pratama@gmail.com',
                'nama_kontak_darurat'     => 'Slamet Pratama',
                'no_hp_kontak_darurat'    => '081234567900',
                'hubungan_kontak_darurat' => 'Ayah',
                'jenis_pelatihan'         => 'Menjahit',
                'program_id'              => 'PROG-MENJAHIT',
                'tempat_pelatihan'        => 'Gedung LPK Leles Utama (Jl. Raya Leles No. 45, Garut)',
                'motivasi'                => 'Saya ingin menguasai keahlian menjahit busana dan membuka usaha konveksi sendiri.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000050',
                'user_id'                 => '22222222-0000-0000-0000-000000000001',
                'biaya_pelatihan'         => 3000000,
                'status_pembayaran'       => 'lunas',
                'jenis_pembayaran'        => 'lunas',
                'metode_pembayaran'       => 'Transfer Bank',
                'bukti_pembayaran'        => 'bukti/pembayaran/andi-pratama-lunas.jpg',
                'tanggal_bayar'           => '2026-04-01 10:30:00',
            ],
            // 2. Siti (diterima, cicilan, Angkatan 50)
            [
                'id'                      => 'PD-000000-0000-0000-000000000002',
                'no_pendaftaran'          => 'LPK-2026-00002',
                'tanggal_daftar'          => '2026-03-12 10:00:00',
                'status'                  => 'diterima',
                'nama_lengkap'            => 'Siti Rahayu',
                'nik'                     => '3275014506990002',
                'tempat_lahir'            => 'Garut',
                'tanggal_lahir'           => '1999-06-05',
                'jenis_kelamin'           => 'Perempuan',
                'alamat'                  => 'Jl. Al-Kautsar No. 45, Leles, Garut',
                'tinggi_badan'            => '158',
                'berat_badan'             => '52',
                'lingkar_pinggang'        => '68',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567802',
                'email'                   => 'siti.rahayu@gmail.com',
                'nama_kontak_darurat'     => 'Aminah',
                'no_hp_kontak_darurat'    => '081234567901',
                'hubungan_kontak_darurat' => 'Ibu',
                'jenis_pelatihan'         => 'Menjahit',
                'program_id'              => 'PROG-MENJAHIT',
                'tempat_pelatihan'        => 'Workshop Menjahit Leles (Jl. Al-Kautsar No. 12, Leles)',
                'motivasi'                => 'Ingin menjadi desainer busana dan penjahit profesional di Garut.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000050',
                'user_id'                 => '22222222-0000-0000-0000-000000000002',
                'biaya_pelatihan'         => 3000000,
                'status_pembayaran'       => 'cicilan_sebagian',
                'jenis_pembayaran'        => 'cicilan',
                'metode_pembayaran'       => 'Transfer Bank',
                'bukti_pembayaran'        => 'bukti/pembayaran/siti-rahayu-dp.jpg',
                'tanggal_bayar'           => '2026-04-02 11:00:00',
            ],
            // 3. Rizky (diterima, lunas, Angkatan 50)
            [
                'id'                      => 'PD-000000-0000-0000-000000000003',
                'no_pendaftaran'          => 'LPK-2026-00003',
                'tanggal_daftar'          => '2026-03-15 13:00:00',
                'status'                  => 'diterima',
                'nama_lengkap'            => 'Rizky Maulana',
                'nik'                     => '3578010310010003',
                'tempat_lahir'            => 'Garut',
                'tanggal_lahir'           => '2001-03-03',
                'jenis_kelamin'           => 'Laki-laki',
                'alamat'                  => 'Jl. Raya Leles No. 88, Garut, Jawa Barat',
                'tinggi_badan'            => '175',
                'berat_badan'             => '72',
                'lingkar_pinggang'        => '82',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567803',
                'email'                   => 'rizky.maulana@gmail.com',
                'nama_kontak_darurat'     => 'Hendra Maulana',
                'no_hp_kontak_darurat'    => '081234567902',
                'hubungan_kontak_darurat' => 'Kakak',
                'jenis_pelatihan'         => 'Menjahit',
                'program_id'              => 'PROG-MENJAHIT',
                'tempat_pelatihan'        => 'Gedung LPK Leles Utama (Jl. Raya Leles No. 45, Garut)',
                'motivasi'                => 'Bermimpi membuka tailor pakaian pria modern.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000050',
                'user_id'                 => '22222222-0000-0000-0000-000000000003',
                'biaya_pelatihan'         => 3000000,
                'status_pembayaran'       => 'lunas',
                'jenis_pembayaran'        => 'lunas',
                'metode_pembayaran'       => 'QRIS',
                'bukti_pembayaran'        => 'bukti/pembayaran/rizky-maulana-lunas.jpg',
                'tanggal_bayar'           => '2026-04-03 09:00:00',
            ],
            // 4. Fitri (menunggu, belum bayar, Angkatan 51)
            [
                'id'                      => 'PD-000000-0000-0000-000000000004',
                'no_pendaftaran'          => 'LPK-2026-00004',
                'tanggal_daftar'          => '2026-08-20 14:30:00',
                'status'                  => 'menunggu',
                'nama_lengkap'            => 'Fitri Handayani',
                'nik'                     => '3471024508020004',
                'tempat_lahir'            => 'Garut',
                'tanggal_lahir'           => '2002-08-05',
                'jenis_kelamin'           => 'Perempuan',
                'alamat'                  => 'Jl. Kadungora No. 22, Garut',
                'tinggi_badan'            => '160',
                'berat_badan'             => '55',
                'lingkar_pinggang'        => '70',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567804',
                'email'                   => 'fitri.handayani@gmail.com',
                'nama_kontak_darurat'     => 'Sumarni',
                'no_hp_kontak_darurat'    => '081234567903',
                'hubungan_kontak_darurat' => 'Ibu',
                'jenis_pelatihan'         => 'Menjahit',
                'program_id'              => 'PROG-MENJAHIT',
                'tempat_pelatihan'        => 'Kampus Cabang Garut Kota (Jl. Ahmad Yani No. 88, Garut)',
                'motivasi'                => 'Ingin bekerja di industri garmen ternama.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000051',
                'user_id'                 => '22222222-0000-0000-0000-000000000004',
                'biaya_pelatihan'         => 3000000,
                'status_pembayaran'       => 'belum_bayar',
                'jenis_pembayaran'        => null,
                'metode_pembayaran'       => null,
                'bukti_pembayaran'        => null,
                'tanggal_bayar'           => null,
            ],
            // 5. Dian (diterima, menunggu konfirmasi bayar, Angkatan 51)
            [
                'id'                      => 'PD-000000-0000-0000-000000000005',
                'no_pendaftaran'          => 'LPK-2026-00005',
                'tanggal_daftar'          => '2026-08-21 10:00:00',
                'status'                  => 'diterima',
                'nama_lengkap'            => 'Dian Permata',
                'nik'                     => '3275091209030005',
                'tempat_lahir'            => 'Garut',
                'tanggal_lahir'           => '2003-09-12',
                'jenis_kelamin'           => 'Perempuan',
                'alamat'                  => 'Jl. Limbangan No. 100, Garut, Jawa Barat',
                'tinggi_badan'            => '155',
                'berat_badan'             => '48',
                'lingkar_pinggang'        => '65',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567805',
                'email'                   => 'dian.permata@gmail.com',
                'nama_kontak_darurat'     => 'Heri Permata',
                'no_hp_kontak_darurat'    => '081234567904',
                'hubungan_kontak_darurat' => 'Ayah',
                'jenis_pelatihan'         => 'Menjahit',
                'program_id'              => 'PROG-MENJAHIT',
                'tempat_pelatihan'        => 'Workshop Menjahit Leles (Jl. Al-Kautsar No. 12, Leles)',
                'motivasi'                => 'Ingin mendapatkan sertifikasi keahlian menjahit resmi.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000051',
                'user_id'                 => '22222222-0000-0000-0000-000000000005',
                'biaya_pelatihan'         => 3000000,
                'status_pembayaran'       => 'menunggu_konfirmasi',
                'jenis_pembayaran'        => 'lunas',
                'metode_pembayaran'       => 'Transfer Bank',
                'bukti_pembayaran'        => 'bukti/pembayaran/dian-permata.jpg',
                'tanggal_bayar'           => '2026-08-22 14:00:00',
            ],
            // 6. Budi (diterima, lunas, Angkatan 49)
            [
                'id'                      => 'PD-000000-0000-0000-000000000006',
                'no_pendaftaran'          => 'LPK-2025-00049',
                'tanggal_daftar'          => '2025-08-15 08:30:00',
                'status'                  => 'diterima',
                'nama_lengkap'            => 'Budi Santoso',
                'nik'                     => '3201011504950006',
                'tempat_lahir'            => 'Garut',
                'tanggal_lahir'           => '1995-05-20',
                'jenis_kelamin'           => 'Laki-laki',
                'alamat'                  => 'Jl. Raya Leles No. 10, Garut',
                'tinggi_badan'            => '168',
                'berat_badan'             => '65',
                'lingkar_pinggang'        => '78',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567806',
                'email'                   => 'budi.santoso@gmail.com',
                'nama_kontak_darurat'     => 'Wawan',
                'no_hp_kontak_darurat'    => '081234567905',
                'hubungan_kontak_darurat' => 'Ayah',
                'jenis_pelatihan'         => 'Menjahit',
                'program_id'              => 'PROG-MENJAHIT',
                'tempat_pelatihan'        => 'Gedung LPK Leles Utama (Jl. Raya Leles No. 45, Garut)',
                'motivasi'                => 'Telah menyelesaikan pelatihan angkatan 49 dengan hasil memuaskan.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000049',
                'user_id'                 => '22222222-0000-0000-0000-000000000006',
                'biaya_pelatihan'         => 3000000,
                'status_pembayaran'       => 'lunas',
                'jenis_pembayaran'        => 'lunas',
                'metode_pembayaran'       => 'Transfer Bank',
                'bukti_pembayaran'        => 'bukti/pembayaran/budi-lunas.jpg',
                'tanggal_bayar'           => '2025-08-25 10:00:00',
            ],
            // 7. Rina (diterima, lunas, Angkatan 49)
            [
                'id'                      => 'PD-000000-0000-0000-000000000007',
                'no_pendaftaran'          => 'LPK-2025-00050',
                'tanggal_daftar'          => '2025-08-18 11:00:00',
                'status'                  => 'diterima',
                'nama_lengkap'            => 'Rina Wulandari',
                'nik'                     => '3201014504980007',
                'tempat_lahir'            => 'Garut',
                'tanggal_lahir'           => '1998-11-12',
                'jenis_kelamin'           => 'Perempuan',
                'alamat'                  => 'Jl. Otista No. 77, Garut',
                'tinggi_badan'            => '157',
                'berat_badan'             => '50',
                'lingkar_pinggang'        => '66',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567807',
                'email'                   => 'rina.wulandari@gmail.com',
                'nama_kontak_darurat'     => 'Tati',
                'no_hp_kontak_darurat'    => '081234567906',
                'hubungan_kontak_darurat' => 'Ibu',
                'jenis_pelatihan'         => 'Menjahit',
                'program_id'              => 'PROG-MENJAHIT',
                'tempat_pelatihan'        => 'Workshop Menjahit Leles (Jl. Al-Kautsar No. 12, Leles)',
                'motivasi'                => 'Belajar jahit pakaian wanita dan gaun pesta.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000049',
                'user_id'                 => '22222222-0000-0000-0000-000000000007',
                'biaya_pelatihan'         => 3000000,
                'status_pembayaran'       => 'lunas',
                'jenis_pembayaran'        => 'lunas',
                'metode_pembayaran'       => 'Transfer Bank',
                'bukti_pembayaran'        => 'bukti/pembayaran/rina-lunas.jpg',
                'tanggal_bayar'           => '2025-08-28 14:00:00',
            ],
            // 8. Dewi (menunggu, belum bayar, Angkatan 51)
            [
                'id'                      => 'PD-000000-0000-0000-000000000008',
                'no_pendaftaran'          => 'LPK-2026-00008',
                'tanggal_daftar'          => '2026-08-23 09:15:00',
                'status'                  => 'menunggu',
                'nama_lengkap'            => 'Dewi Anggraini',
                'nik'                     => '3201014504010008',
                'tempat_lahir'            => 'Garut',
                'tanggal_lahir'           => '2001-01-20',
                'jenis_kelamin'           => 'Perempuan',
                'alamat'                  => 'Jl. Cimanuk No. 55, Garut',
                'tinggi_badan'            => '159',
                'berat_badan'             => '51',
                'lingkar_pinggang'        => '67',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567808',
                'email'                   => 'dewi.anggraini@gmail.com',
                'nama_kontak_darurat'     => 'Bambang',
                'no_hp_kontak_darurat'    => '081234567907',
                'hubungan_kontak_darurat' => 'Ayah',
                'jenis_pelatihan'         => 'Menjahit',
                'program_id'              => 'PROG-MENJAHIT',
                'tempat_pelatihan'        => 'Gedung LPK Leles Utama (Jl. Raya Leles No. 45, Garut)',
                'motivasi'                => 'Ingin mendirikan brand pakaian lokal.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000051',
                'user_id'                 => '22222222-0000-0000-0000-000000000008',
                'biaya_pelatihan'         => 3000000,
                'status_pembayaran'       => 'belum_bayar',
                'jenis_pembayaran'        => null,
                'metode_pembayaran'       => null,
                'bukti_pembayaran'        => null,
                'tanggal_bayar'           => null,
            ],
            // 9. Fajar (diterima, cicilan, Angkatan 50)
            [
                'id'                      => 'PD-000000-0000-0000-000000000009',
                'no_pendaftaran'          => 'LPK-2026-00009',
                'tanggal_daftar'          => '2026-03-18 16:00:00',
                'status'                  => 'diterima',
                'nama_lengkap'            => 'Fajar Ramadhan',
                'nik'                     => '3201011504990009',
                'tempat_lahir'            => 'Garut',
                'tanggal_lahir'           => '1999-10-10',
                'jenis_kelamin'           => 'Laki-laki',
                'alamat'                  => 'Jl. Pembangunan No. 34, Garut',
                'tinggi_badan'            => '170',
                'berat_badan'             => '64',
                'lingkar_pinggang'        => '76',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567809',
                'email'                   => 'fajar.ramadhan@gmail.com',
                'nama_kontak_darurat'     => 'Asep Ramadhan',
                'no_hp_kontak_darurat'    => '081234567908',
                'hubungan_kontak_darurat' => 'Ayah',
                'jenis_pelatihan'         => 'Menjahit',
                'program_id'              => 'PROG-MENJAHIT',
                'tempat_pelatihan'        => 'Kampus Cabang Garut Kota (Jl. Ahmad Yani No. 88, Garut)',
                'motivasi'                => 'Tertarik dengan industri jahit dan sepatu kulit Garut.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000050',
                'user_id'                 => '22222222-0000-0000-0000-000000000009',
                'biaya_pelatihan'         => 3000000,
                'status_pembayaran'       => 'cicilan_sebagian',
                'jenis_pembayaran'        => 'cicilan',
                'metode_pembayaran'       => 'Transfer Bank',
                'bukti_pembayaran'        => 'bukti/pembayaran/fajar-cicilan.jpg',
                'tanggal_bayar'           => '2026-04-05 15:30:00',
            ],
            // 10. Nabila (menunggu, belum bayar, Angkatan 51)
            [
                'id'                      => 'PD-000000-0000-0000-000000000010',
                'no_pendaftaran'          => 'LPK-2026-00010',
                'tanggal_daftar'          => '2026-08-25 11:20:00',
                'status'                  => 'menunggu',
                'nama_lengkap'            => 'Nabila Putri',
                'nik'                     => '3201014504020010',
                'tempat_lahir'            => 'Garut',
                'tanggal_lahir'           => '2002-12-04',
                'jenis_kelamin'           => 'Perempuan',
                'alamat'                  => 'Jl. Samarang No. 19, Garut',
                'tinggi_badan'            => '156',
                'berat_badan'             => '49',
                'lingkar_pinggang'        => '65',
                'riwayat_penyakit'        => null,
                'no_hp'                   => '081234567810',
                'email'                   => 'nabila.putri@gmail.com',
                'nama_kontak_darurat'     => 'Endang',
                'no_hp_kontak_darurat'    => '081234567909',
                'hubungan_kontak_darurat' => 'Ibu',
                'jenis_pelatihan'         => 'Menjahit',
                'program_id'              => 'PROG-MENJAHIT',
                'tempat_pelatihan'        => 'Workshop Menjahit Leles (Jl. Al-Kautsar No. 12, Leles)',
                'motivasi'                => 'Ingin menguasai teknik jahit halus busana muslimah.',
                'angkatan_id'             => 'ANG-0000-0000-0000-000000000051',
                'user_id'                 => '22222222-0000-0000-0000-000000000010',
                'biaya_pelatihan'         => 3000000,
                'status_pembayaran'       => 'belum_bayar',
                'jenis_pembayaran'        => null,
                'metode_pembayaran'       => null,
                'bukti_pembayaran'        => null,
                'tanggal_bayar'           => null,
            ],
        ];

        DB::table('pendaftars')->insert($pendaftars);
    }
}
